version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detail:
    format: '%(asctime)s - %(levelname)s - File: %(filename)s - %(funcName)s() - Line: %(lineno)d -  %(message)s'

loggers:
  all:
    handlers: [all]
    propagate: true
  warn:
    handlers: [warn]
    propagate: true
  ingenia:
    handlers: [ingenia]
    propagate: false
    qualname: ingenia
  tornado:
    handlers: [all]
    propagate: false

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  all:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    when: W0
    backupCount: 10
    filename: ../../logs/all.log
  warn:
    class: logging.handlers.TimedRotatingFileHandler
    level: WARNING
    formatter: detail
    when: W0
    backupCount: 10
    filename: ../../logs/warn.log
  ingenia:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    when: W0
    backupCount: 10
    filename: ../../logs/ingenia.log

root:
  level: INFO
  handlers: [console, all, warn]
  propagate: true